### ISSUE TITLE
Multiple Microros agents 

### ISSUE THREAD

**Issue by Muthulakshimi** [micro-ROS/micro-ROS-Agent#235]
## Issue template

- Hardware description: Using linux PC Ubuntu 22.04.5
- RTOS: none for now later will use teensy 4.0
- Installation type: setting agent in the pc and vm directly without docker
- Version or commit hash: foxy-microros; humble-ros2

#### Steps to reproduce the issue
I used the following commands to run the agent - ros2 run micro_ros_agent micro_ros_agent udp4 --port 2019 (on PC with ip 10.221.38.153) then similarly ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888 (on VM with ip 10.221.38.78) 

I want to try vm as one device pc as another run both the microros agents and connect it to the clients to receive the ping messages respectively. 

#### Expected behavior
Should be able to run the multiple agents for pc and vm acting as separate devices 

#### Actual behavior
I have the agent running 
![image](https://github.com/user-attachments/assets/1d417ac3-98c2-4d1f-9f7d-375a25119170)

the ping gets sent
![image](https://github.com/user-attachments/assets/255aa61b-d8cb-40d7-a7b7-c2485f33b08e)

and is correctly publishing the expected pings
![image](https://github.com/user-attachments/assets/d6421b5c-d13e-4e07-98a4-5cb81844d83d)

This is happening in both the devices separately
Could you please help me with further steps on how to connect both the agents(one of pc other of vm) to the respective clients on each device. so for example I have to pub msgs via say vm agent and this msg has to get subscribed to the vm subscriber(connected to pc agent)
Overall I have to try 
case 1: multiple agents accessing one publisher
case 2: one agent accessing multiple publisher

#### Additional information
I get the impression that multiple agents is possible and listening to the specific agent has a cmd that gives the particular ip address and port via the clients/nodes or some configuration modification please help with the method

**Comment by patrickwasp** [comment]
I think I have a similar issue. When the two agents are on they interfere with each other, causing one or the other to lose connection with their devices. How do I run two agents on one network?

PC1, with serial device connected to USB port

```yaml
  micro-ros-serial-agent:
    image: microros/micro-ros-agent:humble
    privileged: true
    environment:
      - ROS_DOMAIN_ID=8
    network_mode: host
    ipc: host
    command: serial --dev /dev/ttyACM0 --verbose 4
```    

PC2:

  ```yaml  
  micro-ros-udp-agent:
    image: microros/micro-ros-agent:humble
    privileged: true
    network_mode: host
    ipc: host
    init: true
    stop_signal: SIGKILL
    stop_grace_period: 1s
    environment:
      - ROS_DOMAIN_ID=8
    command: udp4 --port 8888 --verbose 4
```
